FROM apache/airflow:2.10.5

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER airflow

RUN pip install --no-cache-dir --no-deps \
    apache-airflow-providers-apache-spark==5.2.1

RUN pip install --no-cache-dir --no-deps \
    apache-airflow-providers-common-compat==1.5.0

RUN pip install --no-cache-dir --no-deps \
    pyspark==4.0.1

RUN pip install --no-cache-dir \
    py4j==0.10.9.9